# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - task -f
    silent: true

  lint:
    cmds:
      - ansible-lint .
    silent: true

  test:
    cmds:
      - molecule test
    silent: true

  test-converge:
    cmds:
      - molecule converge
    silent: true
