---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-24.04
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: systemd

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}

verifier:
  name: testinfra
